### ISSUE TITLE
OpenSSL::CCMError: unsupported cipher algorithm (AES)

### ISSUE THREAD

**Issue by jooeycheng** [jooeycheng/adyen-cse-ruby#11]
Happening on certain environments (CircleCI), still unsure of root cause:
```
OpenSSL::CCMError:
  unsupported cipher algorithm (AES)
./vendor/bundle/ruby/2.5.0/gems/openssl-ccm-1.2.1/lib/openssl/ccm.rb:42:in `initialize'
./vendor/bundle/ruby/2.5.0/gems/adyen-cse-ruby-1.1.0/lib/adyen_cse/encrypter.rb:34:in `new'
./vendor/bundle/ruby/2.5.0/gems/adyen-cse-ruby-1.1.0/lib/adyen_cse/encrypter.rb:34:in `encrypt!'
```
Refer to https://github.com/SmallLars/openssl-ccm/pull/4 for issue explanation.

**Comment by jooeycheng** [comment]
**Temporary fix:**

Add this fork of the `openssl-ccm` gem in your Gemfile:

```ruby
# Gemfile

gem 'adyen-cse-ruby', '1.1.1'
gem 'openssl-ccm', git: 'https://github.com/franee/openssl-ccm'
```

**Comment by jooeycheng** [comment]
@franee could u try this out.

**Comment by franee** [comment]
@jooeycheng yes I can confirm it works.

Another way (monkey-patch) I did for a rails app w/o Gemfile changes.

Create a config/initializers/openssl_ccm_monkey_patch.rb:
```
require 'openssl/ccm'

class OpenSSL::CCM
  def self.ciphers
    @ciphers ||= OpenSSL::Cipher.ciphers.select { |c| c.match(/.+-[12][259][896]-CBC$/i) }.map { |e| e[0..-9].upcase }.uniq
  end
end
```

**Comment by jooeycheng** [comment]
@franee I think that's a better solution!
